// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	dns "github.com/miekg/dns"
	mock "github.com/stretchr/testify/mock"
)

// DNSServer is an autogenerated mock type for the DNSServer type
type DNSServer struct {
	mock.Mock
}

type DNSServer_Expecter struct {
	mock *mock.Mock
}

func (_m *DNSServer) EXPECT() *DNSServer_Expecter {
	return &DNSServer_Expecter{mock: &_m.Mock}
}

// ServeDNS provides a mock function with given fields: w, req
func (_m *DNSServer) ServeDNS(w dns.ResponseWriter, req *dns.Msg) {
	_m.Called(w, req)
}

// DNSServer_ServeDNS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServeDNS'
type DNSServer_ServeDNS_Call struct {
	*mock.Call
}

// ServeDNS is a helper method to define mock.On call
//   - w dns.ResponseWriter
//   - req *dns.Msg
func (_e *DNSServer_Expecter) ServeDNS(w interface{}, req interface{}) *DNSServer_ServeDNS_Call {
	return &DNSServer_ServeDNS_Call{Call: _e.mock.On("ServeDNS", w, req)}
}

func (_c *DNSServer_ServeDNS_Call) Run(run func(w dns.ResponseWriter, req *dns.Msg)) *DNSServer_ServeDNS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(dns.ResponseWriter), args[1].(*dns.Msg))
	})
	return _c
}

func (_c *DNSServer_ServeDNS_Call) Return() *DNSServer_ServeDNS_Call {
	_c.Call.Return()
	return _c
}

func (_c *DNSServer_ServeDNS_Call) RunAndReturn(run func(dns.ResponseWriter, *dns.Msg)) *DNSServer_ServeDNS_Call {
	_c.Run(run)
	return _c
}

// NewDNSServer creates a new instance of DNSServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDNSServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *DNSServer {
	mock := &DNSServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
