// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	goinwx "github.com/nrdcg/goinwx"
	mock "github.com/stretchr/testify/mock"
)

// INWXClient is an autogenerated mock type for the INWXClient type
type INWXClient struct {
	mock.Mock
}

type INWXClient_Expecter struct {
	mock *mock.Mock
}

func (_m *INWXClient) EXPECT() *INWXClient_Expecter {
	return &INWXClient_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with no fields
func (_m *INWXClient) Login() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// INWXClient_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type INWXClient_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
func (_e *INWXClient_Expecter) Login() *INWXClient_Login_Call {
	return &INWXClient_Login_Call{Call: _e.mock.On("Login")}
}

func (_c *INWXClient_Login_Call) Run(run func()) *INWXClient_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *INWXClient_Login_Call) Return(_a0 error) *INWXClient_Login_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *INWXClient_Login_Call) RunAndReturn(run func() error) *INWXClient_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with no fields
func (_m *INWXClient) Logout() {
	_m.Called()
}

// INWXClient_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type INWXClient_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
func (_e *INWXClient_Expecter) Logout() *INWXClient_Logout_Call {
	return &INWXClient_Logout_Call{Call: _e.mock.On("Logout")}
}

func (_c *INWXClient_Logout_Call) Run(run func()) *INWXClient_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *INWXClient_Logout_Call) Return() *INWXClient_Logout_Call {
	_c.Call.Return()
	return _c
}

func (_c *INWXClient_Logout_Call) RunAndReturn(run func()) *INWXClient_Logout_Call {
	_c.Run(run)
	return _c
}

// NameserverCreateRecord provides a mock function with given fields: req
func (_m *INWXClient) NameserverCreateRecord(req *goinwx.NameserverRecordRequest) (string, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for NameserverCreateRecord")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*goinwx.NameserverRecordRequest) (string, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*goinwx.NameserverRecordRequest) string); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*goinwx.NameserverRecordRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// INWXClient_NameserverCreateRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NameserverCreateRecord'
type INWXClient_NameserverCreateRecord_Call struct {
	*mock.Call
}

// NameserverCreateRecord is a helper method to define mock.On call
//   - req *goinwx.NameserverRecordRequest
func (_e *INWXClient_Expecter) NameserverCreateRecord(req interface{}) *INWXClient_NameserverCreateRecord_Call {
	return &INWXClient_NameserverCreateRecord_Call{Call: _e.mock.On("NameserverCreateRecord", req)}
}

func (_c *INWXClient_NameserverCreateRecord_Call) Run(run func(req *goinwx.NameserverRecordRequest)) *INWXClient_NameserverCreateRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*goinwx.NameserverRecordRequest))
	})
	return _c
}

func (_c *INWXClient_NameserverCreateRecord_Call) Return(_a0 string, _a1 error) *INWXClient_NameserverCreateRecord_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *INWXClient_NameserverCreateRecord_Call) RunAndReturn(run func(*goinwx.NameserverRecordRequest) (string, error)) *INWXClient_NameserverCreateRecord_Call {
	_c.Call.Return(run)
	return _c
}

// NameserverDeleteRecord provides a mock function with given fields: id
func (_m *INWXClient) NameserverDeleteRecord(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for NameserverDeleteRecord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// INWXClient_NameserverDeleteRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NameserverDeleteRecord'
type INWXClient_NameserverDeleteRecord_Call struct {
	*mock.Call
}

// NameserverDeleteRecord is a helper method to define mock.On call
//   - id string
func (_e *INWXClient_Expecter) NameserverDeleteRecord(id interface{}) *INWXClient_NameserverDeleteRecord_Call {
	return &INWXClient_NameserverDeleteRecord_Call{Call: _e.mock.On("NameserverDeleteRecord", id)}
}

func (_c *INWXClient_NameserverDeleteRecord_Call) Run(run func(id string)) *INWXClient_NameserverDeleteRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *INWXClient_NameserverDeleteRecord_Call) Return(_a0 error) *INWXClient_NameserverDeleteRecord_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *INWXClient_NameserverDeleteRecord_Call) RunAndReturn(run func(string) error) *INWXClient_NameserverDeleteRecord_Call {
	_c.Call.Return(run)
	return _c
}

// NameserverInfo provides a mock function with given fields: req
func (_m *INWXClient) NameserverInfo(req *goinwx.NameserverInfoRequest) (*goinwx.NameserverInfoResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for NameserverInfo")
	}

	var r0 *goinwx.NameserverInfoResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*goinwx.NameserverInfoRequest) (*goinwx.NameserverInfoResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*goinwx.NameserverInfoRequest) *goinwx.NameserverInfoResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*goinwx.NameserverInfoResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*goinwx.NameserverInfoRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// INWXClient_NameserverInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NameserverInfo'
type INWXClient_NameserverInfo_Call struct {
	*mock.Call
}

// NameserverInfo is a helper method to define mock.On call
//   - req *goinwx.NameserverInfoRequest
func (_e *INWXClient_Expecter) NameserverInfo(req interface{}) *INWXClient_NameserverInfo_Call {
	return &INWXClient_NameserverInfo_Call{Call: _e.mock.On("NameserverInfo", req)}
}

func (_c *INWXClient_NameserverInfo_Call) Run(run func(req *goinwx.NameserverInfoRequest)) *INWXClient_NameserverInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*goinwx.NameserverInfoRequest))
	})
	return _c
}

func (_c *INWXClient_NameserverInfo_Call) Return(_a0 *goinwx.NameserverInfoResponse, _a1 error) *INWXClient_NameserverInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *INWXClient_NameserverInfo_Call) RunAndReturn(run func(*goinwx.NameserverInfoRequest) (*goinwx.NameserverInfoResponse, error)) *INWXClient_NameserverInfo_Call {
	_c.Call.Return(run)
	return _c
}

// TryToUnlockWithOTPKey provides a mock function with given fields: otpKey, retryAfterPauseToSatisfyInwxSingleOTPKeyUsagePolicy
func (_m *INWXClient) TryToUnlockWithOTPKey(otpKey string, retryAfterPauseToSatisfyInwxSingleOTPKeyUsagePolicy bool) (error, error) {
	ret := _m.Called(otpKey, retryAfterPauseToSatisfyInwxSingleOTPKeyUsagePolicy)

	if len(ret) == 0 {
		panic("no return value specified for TryToUnlockWithOTPKey")
	}

	var r0 error
	var r1 error
	if rf, ok := ret.Get(0).(func(string, bool) (error, error)); ok {
		return rf(otpKey, retryAfterPauseToSatisfyInwxSingleOTPKeyUsagePolicy)
	}
	if rf, ok := ret.Get(0).(func(string, bool) error); ok {
		r0 = rf(otpKey, retryAfterPauseToSatisfyInwxSingleOTPKeyUsagePolicy)
	} else {
		r0 = ret.Error(0)
	}

	if rf, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = rf(otpKey, retryAfterPauseToSatisfyInwxSingleOTPKeyUsagePolicy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// INWXClient_TryToUnlockWithOTPKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryToUnlockWithOTPKey'
type INWXClient_TryToUnlockWithOTPKey_Call struct {
	*mock.Call
}

// TryToUnlockWithOTPKey is a helper method to define mock.On call
//   - otpKey string
//   - retryAfterPauseToSatisfyInwxSingleOTPKeyUsagePolicy bool
func (_e *INWXClient_Expecter) TryToUnlockWithOTPKey(otpKey interface{}, retryAfterPauseToSatisfyInwxSingleOTPKeyUsagePolicy interface{}) *INWXClient_TryToUnlockWithOTPKey_Call {
	return &INWXClient_TryToUnlockWithOTPKey_Call{Call: _e.mock.On("TryToUnlockWithOTPKey", otpKey, retryAfterPauseToSatisfyInwxSingleOTPKeyUsagePolicy)}
}

func (_c *INWXClient_TryToUnlockWithOTPKey_Call) Run(run func(otpKey string, retryAfterPauseToSatisfyInwxSingleOTPKeyUsagePolicy bool)) *INWXClient_TryToUnlockWithOTPKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(bool))
	})
	return _c
}

func (_c *INWXClient_TryToUnlockWithOTPKey_Call) Return(_a0 error, _a1 error) *INWXClient_TryToUnlockWithOTPKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *INWXClient_TryToUnlockWithOTPKey_Call) RunAndReturn(run func(string, bool) (error, error)) *INWXClient_TryToUnlockWithOTPKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewINWXClient creates a new instance of INWXClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewINWXClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *INWXClient {
	mock := &INWXClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
